### ISSUE TITLE
parse "" [quote ()]

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#200] opened 2015-12-25 14:33 UTC
src/core/n-data.c:1254: VAL_TYPE_Debug: assertion "NOT_END(v)" failed

**Comment by hostilefork** [comment] 2015-12-26 13:20
As mentioned in chat, the legality of this is in question.  What it is doing is effectively trying to use a non-string, non-character value as a parse rule... UNSET!.  It is illegal to use other arbitrary values as source for a parse rule:

    >> parse "a" ['a]      
    ** Script error: PARSE - invalid rule or usage of rule: 'a
    ** Where: parse
    ** Near: parse "a" ['a]

This should give the same output:

    >> parse "a" [quote a]

And so should this:

     >> parse "a" [quote ('a)]

The fact that it doesn't give the same output is due to QUOTE being buggy.  That buggy-ness leads it to also be buggy in its handling of the case you describe.

1. Does this line up with your understanding?
2. What would you propose the behavior be?

**Comment by hostilefork** [comment] 2016-01-14 01:59
To get this issue closed out of Ren-C (as it might be perceived a regression to "crash")... I've just made QUOTE fail if your input is a string series:

https://github.com/metaeducation/ren-c/commit/95abcd6c58b07148e231df5b3f032aaa23af7949

For a discussion of the general language issue, we now have a place for it (so my comments won't have to be so long anymore...they can go in the issue DB!)  Moving this discussion to rebol-issues:

https://github.com/rebol/rebol-issues/issues/2253

**Closed by hostilefork** 2016-01-14 01:59 UTC
