### ISSUE TITLE
assertion error when probing self

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#293] opened 2016-08-29 22:14 UTC

**Comment by giuliolunati** [comment] 2016-08-29 22:15
```
    probe self
```

Cause assertion error

**Comment by hostilefork** [comment] 2016-08-30 06:38
As mentioned, the problem here is typesets that try to indicate that "void" is a member of the typeset (e.g. what R3-Alpha would have handled as an UNSET!).  The PROBE of SELF was dumping the entire user context, and that meant finding some such typesets and complaining.

Since voids aren't values and don't have types in Ren-C, things have to be done differently.  The issue is hopefully addressed by:

https://github.com/metaeducation/ren-c/commit/6caf195fe503ded463d03019fc4536cd9adcb304

**Closed by hostilefork** 2016-08-30 06:38 UTC
