### ISSUE TITLE
PANIC VALUE called from t-string.c:661

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#301] opened 2016-09-23 18:40 UTC
Using r3 (compiled from commit 
9e6bdf0a2d6cb2f17d77e1c8cfa3d1769ae3200b ) as r3-make and doing `make prep`, found error:

END marker or garbage/trash in VAL_TYPE()
Pointer found in freed tail capacity of series
PANIC VALUE called from ../src/core/t-string.c:6
61
REBVAL init on tick #4441872 at ../src/core/t-string.c:661
Kind=51
Containing series for value pointer found, panicking it:

**Comment by hostilefork** [comment] 2016-09-29 22:48
Eeek, this is another one of those cases with the SINK() macro implicit in Val_Init_Series()!

```
Val_Init_Series(pvs->store, VAL_TYPE(pvs->value), ser);
```

The problem is that `pvs->value` can actually be pointing to `pvs->store`.  So the store gets trashed in some compilers.

I remain to have mixed feelings on this.  On the one hand, SINK is a good macro even in the sense that it is pointing exactly to the problem and the line where it is caused...just as it is supposed to, which makes it useful.  And this case of when input arguments and output arguments are the same is good to call attention to and probably get rid of.  But on the other hand, this problem is not exposing itself well enough.

One way to deal with this would be to make Val_Init_Series an inline function that trashes the destination before it tries to call with the other parameters.  So two lines: SET_TRASH_IF_DEBUG on its own line, and cast(REBVAL*, v) on another.  Yet this undermines the very convenience SINK was supposed to be for in its other uses.

As usual this provides an opportunity to make some piece of unclear code more clear...by figuring out why VAL_TYPE() was even needed in the first place (answer: REB_FILE and REB_URL have the same path dispatch).  And as before I'm torn about how much to mess up the code in order to have the benefit of the check vs. having only some compilers see it.  SINK() is really part of specific binding, to help with RELVALs getting passed in as REBVAL for writing to...and it does its purpose pretty well except for these darn bugs!

Thanks for your patience in any case.  Should be fixed here:

https://github.com/metaeducation/ren-c/commit/376e84d0a3aba585204b61e3a1c3e5e6d0b7aae6

**Closed by hostilefork** 2016-09-29 22:48 UTC

**Comment by hostilefork** [comment] 2017-04-25 10:05
I hit another one of these bugs.  :-/

A lot of time has passed...and the kinds of problems that SINK() inside of these macros was supposed to help find have never been found.  Just another bug caused by it.  So I think it's time to no longer write macros like:

    #define Some_Macro(out, in) \
         Some_Core_Routine(SINK(out), (in))

They're just a bad idea.  In any case, the good thing about having a system with lots of checks in it, is that if one doesn't work out so well... you have a lot more.  :-)
