### ISSUE TITLE
Error "word is not bound" in modules

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#626] opened 2017-10-02 00:02 UTC
When in module

`set 'a 1`

 raises error, while

 `a: 0 set 'a 1`

doesn't

**Comment by hostilefork** [comment] 2017-10-02 00:12
That should happen in "isolated" modules, because there must be a top-level declaration... I think such isolation is expected behavior by default (?)

**Comment by rgchris** [comment] 2017-10-02 00:39
@hostilefork Not quite—isolated modules are explicitly so. 'Regular' modules work by collecting top-level set-words as per objects. @giuliolunati  See [this question](https://stackoverflow.com/q/14420942/292969).

**Comment by hostilefork** [comment] 2017-10-02 05:37
Closing this as not a bug, but #627 was a bug, and should be fixed.

**Closed by hostilefork** 2017-10-02 05:37 UTC
