### ISSUE TITLE
Assertion failure in ../src/include/sys-stack.h, Line 109

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#468] opened 2017-04-12 07:05 UTC
Was dong final test of my source checks changes and run run-recover. then encountered this:

    Assertion failed!

    Program: C:\Projects\Public\renc.exe
    File: ../src/include/sys-stack.h, Line 109

    Expression: NOT(IS_END_MACRO(DS_AT(DSP)))

    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.

**Comment by hostilefork** [comment] 2017-04-12 07:24
As with most asserts, that's a useful one... but that alone can't tell much without a repro.

Feel free to submit the checks with a branch, that reproduces it, and will look at it from there!

**Comment by hostilefork** [comment] 2017-04-12 09:05
I couldn't reproduce your assert on Linux or Windows debug builds.  Given that your changes are all just client code and so there's no breaking of anything that wasn't already broken--I merged it and hopefully within the ecology we'll find a more reliable repro...

Please give info on what settings and platform you used on the build.

Thanks!

**Comment by codebybrett** [comment] 2017-04-12 09:45
Oops, yes info...   Window 10 64bit

I just rebuilt it against commit 4d0b01219cffbfbd689b6f104a576d54bf3c0e3b and it exhibits the same problem.

This is the command file I used to build it:
SET PATH=%PATH%;C:\Qt\Tools\mingw530_32\bin
cd ren-c/make
del objs /s /q
mingw32-make -f makefile.boot

Due to the timing, I expect it is occurring during or at the end of the source analysis, but running source analysis interactively does not cause a problem.

**Comment by hostilefork** [comment] 2017-04-15 03:05
Seems this only reproduced under that configuration with MinGW on Windows, which I had an unusual hassle getting Qt to do *(MinGW 32-bit is not supported by the new Qt beta...and other fun things about the difficulties of installing Qt Creator side-by-side with MSVC and still being able to use GDB)*

But reproduced, and it looks kind of evil.  Not quite sure what's going on.  Looking into it...

**Comment by hostilefork** [comment] 2017-04-15 04:16
Turns out to be the result of an aggressive assert, but a useful assert... so I tweaked it around.  Glad I followed up--it's good to fix!

https://github.com/metaeducation/ren-c/commit/6d69673177c9cfc73f7e1b630199d86eecd187a0

Thanks for the repro...

**Closed by hostilefork** 2017-04-15 04:16 UTC

**Comment by codebybrett** [comment] 2017-04-15 12:29
Sorry you had so much pain to repo it. But it wasn't a good look. Thanks
for following through.
