### ISSUE TITLE
body-of [ ] fails

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#337] opened 2016-11-19 23:08 UTC
sys-context.h:265: VAL_CONTEXT: assertion "ANY_CONTEXT(v)" failed

**Comment by hostilefork** [comment] 2016-11-20 00:46
Known issue, and essentially a duplicate of metaeducation/rebol-issues#2415 (see comments there, add thoughts if you have them...)

**Closed by hostilefork** 2016-11-20 00:46 UTC
