### ISSUE TITLE
Difficulty between the blank and the void.

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#619] opened 2017-08-28 09:32 UTC
Use sometimes the blank and sometimes the void is not simple.
```

>> map-each x [1 2 3 1 2 1] [if x = 1 ["one"]]
== ["one" "one" "one"]

>> map-each x [1 2 3 4 5 1 2 1] [if x > 1 [if x < 3 ["two"]]]
== ["two" _ _ _ "two"]

```

**Comment by hostilefork** [comment] 2017-08-28 13:15
Yes, this does come up.  It is the reason why **IF/ONLY** and friends were created *(aliased as `IF*`, `CASE*`, `EITHER*`...)*, they don't do the "blankification".

    >>  map-each x [1 2 3 4 5 1 2 1] [if* x > 1 [if x < 3 ["two"]]]
    == ["two" "two"]

The native OPT can also be used to convert blanks to voids, passing through all other values...though that's not equivalent since you lose the ability to intentionally return a blank:

    >>  map-each x [1 2 3 4 5 1 2 1] [opt if x > 1 [if x < 3 ["two"]]]
    == ["two" "two"]

It's tough to know how far to take the relationship between a blank and a void.  Should `append copy [a b c] _` append nothing, as `append copy [a b c] []` is nothing, and then require you to use /ONLY (`append*`) to really mean "append the blank"?  Is it any more common for people to mean "really append a blank" than to mean "really append an empty block"?

But I think that people can be more or less aware what's going on.  If you missed this:

https://forum.rebol.info/t/why-or-why-not-have-unset-in-rebol-like-languages/113

**Comment by hostilefork** [comment] 2017-10-18 01:38
Closing as "by design" but if you have opinions please feel free to raise them in the discussion forum.

**Closed by hostilefork** 2017-10-18 01:38 UTC
