### ISSUE TITLE
Ctrl-C causes assert(THROWN(f->out)) during infinite recursive PARSE

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#764] opened 2018-04-02 05:40 UTC
This script demonstrates some odd behaviour:

    REBOL []

    s1: {12x4}
    s2: {5678}

    digit: charset {0123456789}

    test: function [return: <void> string][

        dump string

        rule: [
            any [
                pos:
                [not end (probe pos/1)]
                (assert [same? head pos head string])
                digit
                | skip ((#"x" = pos/1)) (
                    test s2
                )
            ]
        ]

        parse s1 rule
    ]

    test s1

1. I think the assertion should succeed but it fails.
2. If you comment the assertion, you get an infinite loop which is unexpected.
3. CTRL-C from number 2. fairly reliably causes a crash.

**Comment by hostilefork** [comment] 2018-04-02 05:44
Thanks for narrowing that down... I'll see what I can figure out...!

**Comment by hostilefork** [comment] 2018-04-02 16:04
This particular issue seems to be a typo, you said `parse s1 rule`.

`parse string rule` seems to work correctly...

**Comment by codebybrett** [comment] 2018-04-02 21:44
Good grief!!  Sorry.

It's an assertion and is on Windows:  THROWN(f->out assert on line  ..\src\core\c-eval.c   line 1525.
I pulled in latest changes, rebuilt,  same result.

**Comment by hostilefork** [comment] 2019-01-22 13:31
I've never managed to reproduce this crash...and the THROWN(f->out) mechanics have changed a lot since April 2018.  Probably time to close it, and see if it manifests anywhere again someday...

**Closed by hostilefork** 2019-01-22 13:31 UTC
