### ISSUE TITLE
Dark corner for left-normal enfixed params

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#664] opened 2017-12-06 12:40 UTC
`exp 0 + 0 = 1 => true`

but

`exp add 0 0 = 1 => error`

**Comment by hostilefork** [comment] 2017-12-06 12:51
By design, it's just something people have to get used to.  And I think it's something that is good in the sense that when you have an infix operator, you don't have to think to look "arbitrarily far" left to understand its working.  You only look one unit.

The mechanism at work is not "precedence", as the language does not have precedence.

The consequences of infix completing more than one expression on the left are too problematic, as you might recall here:

https://github.com/metaeducation/ren-c/issues/510

**Comment by hostilefork** [comment] 2017-12-06 12:58
Hm, this is different than what you posted in chat.  I will look at it in the morning.

**Comment by giuliolunati** [comment] 2017-12-11 10:02
Now that you explained, no more so dark to me -- maybe `1 + 2 + 3 = 6 => error` would be darker....
I'm slightly favorable to *status quo*

**Comment by hostilefork** [comment] 2017-12-11 15:50
Ok, closing as "by design" for now.  But keep an eye out for problems...it's good that you are looking at the cases.

Thanks for studying it!

**Closed by hostilefork** 2017-12-11 15:50 UTC
