### ISSUE TITLE
Comparing MAP! values crashes the interpreter

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#614] opened 2017-08-16 05:20 UTC
Example:

```
>> map-a: make map! ["a" "a"]
== make map! [
    "a" "a"
]

>> map-b: make map! ["a" "a"] 
== make map! [
    "a" "a"
]

>> equal? map-a map-b
Assertion failed: (ANY_ARRAY(v)), function VAL_ARRAY, file ../src/include/sys-array.h, line 353.
Abort trap: 6
```

**Comment by hostilefork** [comment] 2017-08-16 05:44
Duplicate of:

https://github.com/metaeducation/ren-c/issues/322

Please add comments there...

**Closed by hostilefork** 2017-08-16 05:44 UTC
