### ISSUE TITLE
compile error: specified size [...] exceeds maximum object size 

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#545] opened 2017-06-13 16:08 UTC
```
gcc  -c -DTO_LINUX -DTO_LINUX_X64 -DREB_API   -O2  -Werror  -Wextra -Wall -Wchar-subscripts -Wwrite-strings -Wundef -Wformat=2 -Wdisabled-optimization -Wlogical-op -Wredundant-decls -Woverflow -Wpointer-arith -Wparentheses -Wmain -Wsign-compare -Wtype-limits -Wclobbered -Wno-long-long -Wno-cast-qual -Wno-conversion -Wno-strict-overflow -D__LP64__ -DENDIAN_LITTLE -DHAS_LL_CONSTS -fvisibility=hidden -D_FILE_OFFSET_BITS=64 -DUSE_PIPE2_NOT_PIPE  -I. -I../src/include/   ../src/core/f-random.c -o objs/f-random.o
In file included from /usr/include/string.h:639:0,
                 from ../src/include/sys-core.h:79,
                 from ../src/core/f-deci.c:48:
In function ‘memcpy’,
    inlined from ‘m_to_string’ at ../src/core/f-deci.c:1163:5:
/usr/include/bits/string3.h:53:10: error: ‘__builtin___memcpy_chk’: specified size between 18446744065119617024 and 18446744073709551612 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

failing git commit: 6c7823c9
last known good commit: 38d5202c
on linux 64 (Manjaro Linux)

$ gcc --version
gcc (GCC) 7.1.1 20170528
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zsx** [comment] 2017-06-13 16:46
Could you show us the complete compiling command? and the version of the compiler?

**Comment by IngoHohmann** [comment] 2017-06-26 14:41
Sorry for coming back so late, and for pasting in an incomplete line.
Original comment updated.

**Comment by zsx** [comment] 2017-06-26 19:12
hmm, no problem here:
```
zsx@touchsmart-arch:~/work/ren-c.git/make$ git checkout 6c7823c
HEAD is now at 6c7823c9... Pass a local file to the browser
zsx@touchsmart-arch:~/work/ren-c.git/make$ gcc  -c -DTO_LINUX -DTO_LINUX_X64 -DREB_API   -O2  -Werror  -Wextra -Wall -Wchar-subscripts -Wwrite-strings -Wundef -Wformat=2 -Wdisabled-optimization -Wlogical-op -Wredundant-decls -Woverflow -Wpointer-arith -Wparentheses -Wmain -Wsign-compare -Wtype-limits -Wclobbered -Wno-long-long -Wno-cast-qual -Wno-conversion -Wno-strict-overflow -D__LP64__ -DENDIAN_LITTLE -DHAS_LL_CONSTS -fvisibility=hidden -D_FILE_OFFSET_BITS=64 -DUSE_PIPE2_NOT_PIPE  -I. -I../src/include/   ../src/core/f-random.c -o objs/f-random.o
zsx@touchsmart-arch:~/work/ren-c.git/make$ gcc --version
gcc (GCC) 7.1.1 20170528
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This is on 64-bit Arch Linux.

**Comment by IngoHohmann** [comment] 2017-06-28 20:58
Well, I normally compile with RIGOROUS=YES if I try without this, it compiles for me as well, it fails with RIGOROUS=yes.

Commit:    4ef83d96190527dbcabe46040d1347cbe66f8bac

**Comment by zsx** [comment] 2017-06-29 03:01
Works fine here, and here's the command I used to build:

```
make -f makefile.boot RIGOROUS=yes DEBUG=symbols REBOL_TOOL=./r3-linux-x64-gbf237fc-static
```

**Comment by IngoHohmann** [comment] 2017-07-29 17:02
Compiles again under RIGOROUS=yes with 
Commit: 72ceeb1d
(Maybe from RIGOROUS=yes changes for msvc)

**Comment by hostilefork** [comment] 2018-01-15 01:46
This just tripped for me, for the first time, using @giuliolunati's plain %make.r script with no options.  Same file, %f-deci.c...same error.

Looking into what the problem is.

**Comment by hostilefork** [comment] 2018-01-15 03:33
Well, seems to be addressed in this commit...which also updates the header comment a bit and brings back the inlining annotations (as static inline) from the R3-Alpha version:

https://github.com/metaeducation/ren-c/commit/2d9b2c3f83e4336056f598e7fe48d9fc081150c6

It seems that people more or less suggest this kind of approach is good for money calculations.  But it's unfortunate that this is all original code on the matter, with the original author gone.  :-(

It probably should have been some standalone open source library which might have wound up getting used and fixed by other projects, like [dtoa.c](http://www.netlib.org/fp/dtoa.c).

**Closed by hostilefork** 2018-01-15 03:33 UTC
