### ISSUE TITLE
words-of crashes on block

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#477] opened 2017-04-23 20:01 UTC
**    Version:   2.102.0.3.40                                           **
**    Platform:  Windows win32-x64                                      **
**    Build:     18-Apr-2017/13:41:53                                   **
**    Commit:    615af399c17089c68f2b14bfca88c5c3a38186e2               **

>> words-of []
Assertion failed!

Program: C:\Users\Graham\rebol3\r3.exe
File: ../src/include/sys-context.h, Line 258

Expression: ANY_CONTEXT(v)

**Comment by hostilefork** [comment] 2017-04-24 06:53
Duplicate of #311

**Closed by hostilefork** 2017-04-24 06:53 UTC
